name: Alchemist Build

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          touch .env
          echo "DATABASE_URL=env.DATABASE_URL >> .env
          cat .env
      - name: Install SQLX
        run: cargo install sqlx-cli
      - name: Prep
        run: cargo sqlx prepare
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
