name: Alchemist Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SQLX
      run: cargo install sqlx
    - name: Prep
      run: cargo sqlx prepare
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
